name: GTFS Aggregation Database

on:
  push:
    paths:
      - "gtfsAggregation/postgres_schema.sql"
      - "gtfsAggregation/postgres_static_schema.sql"
      - "docker-compose.yml"

jobs:
  rebuild:
    name: Rebuild database
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    environment: prod # Protect deployments to main branch with approval requirements
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Rebuild database
        run: docker compose down -v

      - name: Build aggregator image and start database
        env:
          API_KEY: ${{ secrets.GTFS_API_KEY }}
          STATIC_API_KEY: ${{ secrets.GTFS_REGIONAL_STATIC_API_KEY }}
          POSTGRES_DSN: postgres://postgres:postgres@db:5432/forseningskartan?sslmode=disable
          STATIC_POSTGRES_DSN: postgres://postgres:postgres@db:5432/forseningskartan_static?sslmode=disable
        run: |
          docker compose build aggregator
          docker compose up -d db aggregator
